system: opentelemetry-demo
sources:
  - id: opentelemetry-demo
    kind: git
    location: https://github.com/open-telemetry/opentelemetry-demo.git
    purpose: repository
    revision: 2e05c45b85b985a691cc75082c234e8d6ac0b2e9
    root_path: .
    include_patterns:
      - README.md
      - compose*.yaml
      - src/**/Dockerfile
